### History

This was an attempt to do LSTMs using the `PyTorchOperation` approach that I tried in convolutions.

# Notebook

In [1]:
# Add Lincoln to system path
import sys
sys.path.append("/Users/seth/development/lincoln/")

In [2]:
# imports
from torch import Tensor
import torch

from typing import Tuple, Dict, List

In [3]:
# Operation with multiple inputs, gradients
class Operation(object):

    def __init__(self):
        pass

    def forward(self, *inputs) -> Tuple[Tensor]:

        self.inputs = inputs

        self.outputs = self._outputs()

        return self.outputs


    def backward(self, *output_grads) -> Tuple[Tensor]:

        assert_same_shapes(self.outputs, output_grads)

        self._compute_grads(output_grads)

        assert_same_shapes(self.inputs, self.input_grads)
        return self.input_grads


    def _compute_grads(self, output_grads: Tuple[Tensor]) -> Tensor:
        
        self.input_grads = self._input_grads(output_grads)

        return self.input_grads

    def _outputs(self) -> Tuple[Tensor]:
        raise NotImplementedError()

    def _input_grads(self, *output_grads) -> Tuple[Tensor]:
        raise NotImplementedError()

In [4]:
# Multiply class
class Multiply(Operation):
   
    def __init__(self):
        pass

    def _outputs(self) -> Tuple[Tensor]:
        '''
        Element-wise multiplication
        '''
        assert len(self.inputs) == 2
        
        return self.inputs[0] * self.inputs[1]

    def _input_grads(self, output_grads: Tuple[Tensor]) -> Tuple[Tensor]:

        return self.inputs[1] * output_grads[0],\
               self.inputs[0] * output_grads[0]
     

In [5]:
# assert_same_shapes function
def assert_same_shapes(tensors: Tuple[Tensor],
                       tensor_grads: Tuple[Tensor]):
    if len(tensors) == 1:
        tensors = tensors[0]
    if len(tensor_grads) == 1:
        tensor_grads = tensor_grads[0]        

    for tensor, tensor_grad in zip(tensors, tensor_grads):
        assert tensor.shape == tensor_grad.shape, \
        '''
        Two tensors should have the same shape; instead, first Tensor's shape is {0}
        and second Tensor's shape is {1}.
        '''.format(tuple(tensor_grad.shape), tuple(tensor.shape))
        return None

In [6]:
# define inputs to Multiply Operation
m = Multiply()
torch.manual_seed(102218)
m1, m2 = torch.rand(2,2), torch.rand(2,2)

In [7]:
# test Multiply (Operation with multiple inputs) forward
m.forward(m1, m2) # tuple of length 1

tensor([[0.8841, 0.2608],
        [0.1206, 0.4546]])

In [8]:
# test Multiply (Operation with multiple inputs) backward
m_grad = torch.ones_like(m1)
m.backward(m_grad)

(tensor([[0.9344, 0.4609],
         [0.4948, 0.5119]]), tensor([[0.9462, 0.5658],
         [0.2438, 0.8881]]))

## PyTorch `Multiply`

### Without the class

In [9]:
# m1 initially
print(m1)
print(m1.requires_grad)

tensor([[0.9462, 0.5658],
        [0.2438, 0.8881]])
False


In [10]:
# detach to copy values
m1_g = m1.detach()
m2_g = m2.detach()

In [11]:
# require gradients
m1_g.requires_grad = True
m2_g.requires_grad = True

In [12]:
# perform operation
out = m1_g * m2_g

In [13]:
# define grad
mul_grad = torch.ones_like(out)

In [14]:
# send gradient backward
out.backward(gradient=mul_grad)

In [15]:
# same gradients as above!
print(m1_g.grad)
print(m2_g.grad)

tensor([[0.9344, 0.4609],
        [0.4948, 0.5119]])
tensor([[0.9462, 0.5658],
        [0.2438, 0.8881]])


### `PyTorchOperation` base class

In [16]:
# PyTorch Operation class
class PyTorchOperation(Operation):

    def __init__(self) -> Tensor:
        super().__init__()


    def forward(self, *inputs) -> Tuple[Tensor]:

        self.inputs = inputs

        self.inputs_with_grad = self._inputs_autograd()
        
        self.outputs = self._outputs()

        return self.outputs
        
        
    def _outputs(self) -> Tuple[Tensor]:
        raise NotImplementedError
        

    def _inputs_autograd(self) -> Tuple[Tensor]:
        inputs_with_grad = tuple(inp.detach() for inp in self.inputs)
        for inp in inputs_with_grad:
            inp.requires_grad = True
        return inputs_with_grad
        

    def _input_grads(self, output_grads: Tensor) -> Tensor:

        for out, grad in zip(self.outputs, output_grads):
            out.backward(gradient=grad)

        input_grads = tuple()
        for inp in self.inputs_with_grad:
            input_grads = input_grads + (inp.grad,)
        
        return input_grads

In [17]:
# Multiply_PyTorch class
class Multiply_PyTorch(PyTorchOperation):
   
    def __init__(self):
        super().__init__()

    def _outputs(self) -> Tuple[Tensor]:
        
        assert len(self.inputs) == 2
        
        return self.inputs_with_grad[0] * self.inputs_with_grad[1],

In [18]:
# Initialize Multiply stuff
m = Multiply_PyTorch()
mp1, mp2 = torch.rand(2,2), torch.rand(2,2)

In [19]:
# Print initial tensors
print(mp1, mp2)

tensor([[0.3988, 0.1799],
        [0.6886, 0.0705]]) tensor([[0.3258, 0.4976],
        [0.6935, 0.2254]])


In [20]:
# Forward
m.forward(mp1, mp2)

(tensor([[0.1299, 0.0895],
         [0.4775, 0.0159]], grad_fn=<ThMulBackward>),)

In [21]:
# Initialize grad and backward
m.backward(torch.ones_like(mp1))

(tensor([[0.3258, 0.4976],
         [0.6935, 0.2254]]), tensor([[0.3988, 0.1799],
         [0.6886, 0.0705]]))

## More complicated example

* Divide two inputs into:
    * `A`, `B`
    * `A` gets copied into `A1` and `A2`
    * `A1` and `A2` each get multiplied, bias added, activation, to create `C1` and `C2`.
    * These get added together to create `D`.
    * `B` and `D` get multiplied to create `E`. 
    
Then the question is: what is the gradient of `E` with respect to `A`.

### Without class

In [22]:
from lincoln.operations.operations import WeightMultiply
from lincoln.operations.operations import BiasAdd

#### Define base operations

In [111]:
# Copy class - 1 to many
class Copy(Operation):
   
    def __init__(self, num=2):
        self.num = num

    def _outputs(self) -> Tuple[Tensor]:
        '''
        Element-wise multiplication
        '''
        output = tuple()
        for i in range(self.num):
            output = output + self.inputs
            
        return output

    def _input_grads(self, output_grads: Tuple[Tensor]) -> Tensor:
        input_grad = torch.zeros_like(output_grads[0])
        for grad in output_grads:
             input_grad = input_grad + grad
        return input_grad

In [112]:
# Add2 Operation
class Add2(Operation):
   
    def __init__(self):
        pass

    def _outputs(self) -> Tuple[Tensor]:
        '''
        Element-wise addition
        '''
        assert len(self.inputs) == 2
        
        return self.inputs[0] + self.inputs[1]

    def _input_grads(self, output_grads: Tuple[Tensor]) -> Tuple[Tensor]:

        return output_grads[0], output_grads[0]
     

In [113]:
# Concat operation - two to one
class Concat2(Operation):
   
    def __init__(self):
        pass

    def _outputs(self) -> Tensor:
        '''
        Element-wise multiplication
        '''
        assert len(self.inputs) == 2
        
        self.input_shapes = [inp.shape[1] for inp in self.inputs]
        
        return torch.cat(list(self.inputs), dim=1)

    def _input_grads(self, output_grads: Tuple[Tensor]) -> Tuple[Tensor]:
        return torch.split(output_grads[0], 
                           self.input_shapes,
                           dim=1)

In [114]:
# printing "a" and "b" tensors
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [116]:
c = Concat2()
out = c.forward(a,b)
print(out)
c.backward(torch.ones_like(out))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


(tensor([[1., 1.],
         [1., 1.]]), tensor([[1., 1.],
         [1., 1.]]))

**TODO**: incorporate these into Lincoln somehow

In [117]:
# initialize tensors
torch.manual_seed(102218)
a, b = torch.rand(2,2), torch.rand(2,2)
w1, w2 = torch.rand(2,2), torch.rand(2,2)
b1, b2 = torch.rand(1,2), torch.rand(1,2)

In [118]:
# set requires_grad = True for all tensors
for t in [a, b, w1, w2, b1, b2]:
    t.requires_grad = True

In [119]:
# define operations
c = Copy()
add2 = Add2()
mul = Multiply()
wm1 = WeightMultiply(w1)
ba1 = BiasAdd(b1)
wm2 = WeightMultiply(w2)
ba2 = BiasAdd(b2)

In [120]:
# define forward path
a1, a2 = c.forward(a)
c1 = ba1.forward(wm1.forward(a1))
c2 = ba2.forward(wm2.forward(a2))
d = add2.forward(c1, c2)
e = mul.forward(b, d)

In [121]:
e # output

tensor([[2.4230, 1.1577],
        [1.2516, 1.0909]], grad_fn=<ThMulBackward>)

In [122]:
torch.sum(e) # sum

tensor(5.9232, grad_fn=<SumBackward0>)

In [123]:
a.grad # None

In [124]:
# passing gradient backwards
e.backward(gradient=torch.ones_like(e))

In [125]:
# all grads work
print(a.grad)

print(b.grad)

print(w1.grad)

print(b1.grad)

tensor([[0.9893, 1.4278],
        [0.7053, 0.8353]])
tensor([[2.5932, 2.5116],
        [2.5298, 2.1312]])
tensor([[1.0048, 0.5609],
        [0.9681, 0.7154]])
tensor([[1.4291, 0.9728]])


This implies that increasing `a[0][0]` by `0.1` will increase the sum from `5.9232` to `5.9232 + 0.1 * 0.9893`.

In [126]:
# define what sum with "a_new" should be: 
5.9232 + 0.1 * 0.9893

6.02213

In [127]:
# define helper function
def sum_with_a(a):
    a1, a2 = c.forward(a)
    c1 = ba1.forward(wm1.forward(a1))
    c2 = ba2.forward(wm2.forward(a2))
    d = add2.forward(c1, c2)
    e = mul.forward(b, d)
    return torch.sum(e)

In [128]:
# define new version of a with one value incremented
a_new = a.clone()
a_new[0][0] += 0.1
print(a_new)

tensor([[1.0462, 0.5658],
        [0.2438, 0.8881]], grad_fn=<CopySlices>)


In [129]:
# test that sum equals expected i.e. that gradients are correct
print(sum_with_a(a))
print(sum_with_a(a_new))

tensor(5.9232, grad_fn=<SumBackward0>)
tensor(6.0222, grad_fn=<SumBackward0>)


Works!

### Turning this into a class

`Layer` class:

* Has forward and backward methods. These simply loop through the operations, passing things forwards or backards.
* On setup, requires a `num_in`

`AutogradBlock` class:

* Has forward method, which calls the `_output` method and `_setup` if it is the first iteration.
* On setup, requires we define all ops in a `Dict[Operation]`. In addition, we define weights and give them a gradient.
* On `_output`, we actually compute the output from the inputs.
* We get the `param_grads` in a similar way we get them from `Layer`s - looping through a dictionary now instead of through a list.

Trouble is: this solution begs the question: why not write an autograd library and do everything that way?

Options for autograd from scratch:

* Could invest a week and unpack the example at `autodiff` in README.
   * He makes heavy use of `einsum`, which is its own overhead.
* Just use PyTorch (bad - why the operations? Might be ok to illustrate LSTM). 

Point is to illustrate how things work. Period.

In [130]:
# Import lincoln operations
from lincoln.operations.operations import WeightMultiply
from lincoln.operations.operations import BiasAdd
from lincoln.operations.base import ParamOperation
from lincoln.operations.activations import Sigmoid, Tanh

In [254]:
# AutogradBlock: block of operations with multiple inputs and outputs
class AutogradBlock(object):

    def __init__(self) -> Tensor:
        super().__init__()
        self.params: Dict[Tensor] = {}
        self.param_grads: List[Tensor] = []
        self.ops: Dict[Operation] = {}
        self.first: bool = True

            
    def _setup_block(self) -> Tuple[Tensor]:
        pass
        

    def forward(self, *inputs) -> Tuple[Tensor]:

        if self.first:
            self._setup_block()
            self.first = False
            
        self.inputs = inputs
        
        self.inputs_with_grad = self._inputs_autograd()
        
        self.params_with_grad = self._params_autograd()
        self._gradify_operations()

        self.outputs = self._outputs()

        return self.outputs

    def _inputs_autograd(self) -> Tuple[Tensor]:
        inputs_with_grad = tuple(inp.detach() for inp in self.inputs)
        for inp in inputs_with_grad:
            inp.requires_grad = True
        return inputs_with_grad

    
    def _params_autograd(self) -> Tuple[Tensor]:
        params_with_grad = tuple(param.detach() for param in self.params.values())
        for param in params_with_grad:
            param.requires_grad = True
        return params_with_grad
    

    def _gradify_operations(self) -> Tuple[Tensor]:
        for op, tensor in zip([op for op in self.ops.values() 
                               if issubclass(op.__class__, ParamOperation)],
                              self.params_with_grad):
            setattr(op, "param", tensor)
    
    
    def backward(self, *output_grads) -> Tuple[Tensor]:

        assert_same_shapes(self.outputs, output_grads)

        self.input_grads = self._input_grads(output_grads)
        
        if self.params:
            self.param_grads = self._param_grads()
    
        assert_same_shapes(self.inputs, self.input_grads)
        return self.input_grads


    def _outputs(self) -> Tuple[Tensor]:
        raise NotImplementedError()


    def _input_grads(self, output_grads: Tuple[Tensor]) -> Tuple[Tensor]:
        
        if len(output_grads) == 1:
            self.outputs.backward(output_grads)
        else: 
            for out, grad in zip(self.outputs, output_grads):
                out.backward(gradient=grad, retain_graph=True)

        input_grads = tuple()
        for inp in self.inputs_with_grad:
            input_grads = input_grads + (inp.grad,)
        
        return input_grads

    
    def _param_grads(self) -> List[Tensor]:
        return tuple(param.grad for param in self.params_with_grad)

    
    def _params(self) -> None:
        return tuple(param.data for param in self.params_with_grad)

In [255]:
# ToyExample class, inheriting from AutogradBlock. 
# Analogous to a custom Layer
class ToyExample(AutogradBlock):
   
    def __init__(self, 
                 seed=12345):
        super().__init__()
        self.seed = seed
    
        
    def _setup_block(self) -> Tuple[Tensor]:

        torch.manual_seed(self.seed)

        self.ops['cp'] = Copy()
        self.ops['add2'] = Add2()
        self.ops['mul'] = Multiply()
        
        self.params['w1'] = torch.rand(2,2)
        self.ops['wm1'] = WeightMultiply(self.params['w1'])
        
        self.params['w2'] = torch.rand(2,2)
        self.ops['wm2'] = WeightMultiply(self.params['w2'])
        
        self.params['b1'] = torch.rand(1,2)
        self.ops['ba1'] = BiasAdd(self.params['b1']) 
        
        self.params['b2'] = torch.rand(1,2)
        self.ops['ba2'] = BiasAdd(self.params['b2'])

        
    def _outputs(self) -> Tuple[Tensor]:
        
        a, b = self.inputs_with_grad 
        a1, a2 = self.ops['cp'].forward(a) 
        c1 = self.ops['ba1'].forward(self.ops['wm1'].forward(a1))
        c2 = self.ops['ba2'].forward(self.ops['wm2'].forward(a2))
        d = self.ops['add2'].forward(c1, c2)
        
        return self.ops['mul'].forward(b, d)

In [256]:
# instantiate
t = ToyExample(seed=102218)

In [257]:
# new input tensors
torch.manual_seed(102218)
a = torch.rand(2,2)
b = torch.rand(2,2)

In [258]:
# result
out = t.forward(a, b)
print(out)
print(torch.sum(out))

tensor([[3.0692, 0.9283],
        [1.0894, 0.8928]], grad_fn=<ThMulBackward>)
tensor(5.9798, grad_fn=<SumBackward0>)


In [259]:
a.grad # no grad

In [260]:
# sending gradient backwards
t.backward(torch.ones_like(out))

(tensor([[2.2304, 1.3354],
         [1.4560, 1.0821]]), tensor([[3.2847, 2.0140],
         [2.2020, 1.7442]]))

In [261]:
a.grad # still no grad

#### Testing gradients

In [262]:
# new version of a
a_new = a.clone()
a_new[0][0] += 0.1
print(a_new)

tensor([[1.0462, 0.5658],
        [0.2438, 0.8881]])


In [263]:
# printing what output should be
out_new = t.forward(a_new, b)
print(out_new)
print(torch.sum(out_new))

tensor([[3.2449, 0.9756],
        [1.0894, 0.8928]], grad_fn=<ThMulBackward>)
tensor(6.2028, grad_fn=<SumBackward0>)


In [264]:
# predicted value
# old_sum + 0.1 * gradient
5.9798 + 0.1 * 2.2304

6.20284

Works!

#### Testing `param_grads`

In [265]:
# we have grads
t.param_grads

(tensor([[1.0048, 0.5609],
         [0.9681, 0.7154]]), tensor([[1.0048, 0.5609],
         [0.9681, 0.7154]]), tensor([[1.4291, 0.9728]]), tensor([[1.4291, 0.9728]]))

In [266]:
# we have grads
for val in t.params.values():
    print(val)

tensor([[0.9462, 0.5658],
        [0.2438, 0.8881]])
tensor([[0.9344, 0.4609],
        [0.4948, 0.5119]])
tensor([[0.3988, 0.1799]])
tensor([[0.6886, 0.0705]])


### LSTMs and beyond

LSTM Node will be an `AutogradBlock` with three inputs and three outputs. 

LSTM Layer, on the other hand...

## LSTM using `AutogradBlock`

#### `LSTMLayer`
* Will have params.
* Instead of `operations` will have `AutogradBlocks`

#### `LSTMNode`
* `AutogradBlock`
* `forward` method will take in `params` as an argument
* `backward` method will produce `input_grads`, and also need to increment the overall `param_grads`
    * Latter should be ok as long as we have `requires_grad = True` for the params passed into the `Node`
    

In [347]:
# LSTMNode series of operations
class LSTMNode(AutogradBlock):
    
    def __init__(self, 
                 hidden_size: int,
                 vocab_size: int,
                 seed: int=12345):

        super().__init__()
        self.seed = seed
        self.hidden_size = hidden_size
        self.vocab_size = vocab_size

        
    def forward(self, 
                lstm_params: Dict[str, Tensor],
                *inputs) -> Tuple[Tensor]:

        if self.first:
            self._setup_block(lstm_params)
            self.first = False
            
        self.inputs = inputs
        
        self.inputs_with_grad = self._inputs_autograd()
        
        self.params_with_grad = self._params_autograd()
        self._gradify_operations()

        self.outputs = self._outputs()

        return self.outputs

    
    def backward(self, 
                 lstm_params: Dict[str, Tensor],
                 *output_grads) -> Tuple[Tensor]:

        assert_same_shapes(self.outputs, output_grads)

        self.input_grads = self._input_grads(output_grads)

        if self.params:
            self.param_grads = self._param_grads()

        assert_same_shapes(self.inputs, self.input_grads)
        return self.input_grads

    
    def _setup_block(self,
                     lstm_params: Dict[str, Tensor]) -> Tuple[Tensor]:

        torch.manual_seed(self.seed)

        self.ops['con'] = Concat2()
        self.ops['copy'] = Copy(4)
        self.ops['sig1'] = Sigmoid()
        self.ops['sig2'] = Sigmoid()
        self.ops['sig3'] = Sigmoid()
        self.ops['tan1'] = Tanh()
        self.ops['tan2'] = Tanh()
        self.ops['mul1'] = Multiply()
        self.ops['mul2'] = Multiply()
        self.ops['mul3'] = Multiply()
        self.ops['add1'] = Add2()
        self.ops['add2'] = Add2()
#         import pdb; pdb.set_trace()
        self.ops['Wf'] = WeightMultiply(lstm_params['Wf'])
        self.ops['Bf'] = BiasAdd(lstm_params['Bf'])
        
        self.ops['Wi'] = WeightMultiply(lstm_params['Wi'])
        self.ops['Bi'] = BiasAdd(lstm_params['Bi'])
        
        self.ops['Wc'] = WeightMultiply(lstm_params['Wc'])
        self.ops['Bc'] = BiasAdd(lstm_params['Bc'])

        self.ops['Wo'] = WeightMultiply(lstm_params['Wo'])
        self.ops['Bo'] = BiasAdd(lstm_params['Bo'])        

        self.ops['Wv'] = WeightMultiply(lstm_params['Wv'])
        self.ops['Bv'] = BiasAdd(lstm_params['Bv'])  
        
        
    def _outputs(self) -> Tuple[Tensor]:
        
        X_in, H_in, C_in = self.inputs_with_grad 
        Z = self.ops['con'].forward(X_in, H_in)
        z1, z2, z3, z4 = self.ops['copy'].forward(Z) 
#         import pdb; pdb.set_trace()
        F = self.ops['Wf'].forward(z1)
        F = self.ops['Bf'].forward(F)
        F_out = self.ops['sig1'].forward(F)

        I = self.ops['Wi'].forward(z2)
        I = self.ops['Bi'].forward(I)
        I_out = self.ops['sig2'].forward(I)
        
        C = self.ops['Wc'].forward(z3)
        C = self.ops['Bc'].forward(C)
        C_bar = self.ops['tan1'].forward(C)
        
        c1 = self.ops['mul1'].forward(F_out, C_in)
        c2 = self.ops['mul2'].forward(I_out, C_bar)
        
        C_out = self.ops['add1'].forward(c1, c2)

        O = self.ops['Wo'].forward(z4)
        O = self.ops['Bo'].forward(O)
        O_out = self.ops['sig3'].forward(O)
        
        C_tan = self.ops['tan2'].forward(c_new)
        H_out = self.ops['mul3'].forward(O_out, C_tan)

        X = self.ops['Wv'].forward(H_out)
        X_out = self.ops['Bv'].forward(X)
        print(H_out[:5, :5])
        return X_out, H_out, C_out

In [348]:
# LSTMLayer class - series of operations
class LSTMLayer(object):
    
    def __init__(self, 
                 max_len: int,
                 vocab_size: int,
                 hidden_size: int = 100):
        super().__init__()
        self.nodes = [LSTMNode(hidden_size, vocab_size) for _ in range(max_len)]
        self.vocab_size = vocab_size
        self.hidden_size = hidden_size
        self.first: bool = True
        self.start_H: Tensor = None
        self.start_C: Tensor = None
        self.params: Dict[Tensor] = {}
        
    
    def _init_params(self, input_: Tensor) -> Tensor:
        '''
        First dimension of input_ will be batch size
        '''
        self.start_H = torch.zeros(input_.shape[0], self.hidden_size)
        self.start_C = torch.zeros(input_.shape[0], self.hidden_size)
        self.params['Wf'] = torch.rand(self.hidden_size + self.vocab_size, 
                                       self.hidden_size)
        self.params['Bf'] = torch.rand(1, self.hidden_size)        

        self.params['Wi'] = torch.rand(self.hidden_size + self.vocab_size, 
                                       self.hidden_size)
        self.params['Bi'] = torch.rand(1, self.hidden_size)
        
        self.params['Wc'] = torch.rand(self.hidden_size + self.vocab_size, 
                                       self.hidden_size)
        self.params['Bc'] = torch.rand(1, self.hidden_size)
    
        self.params['Wo'] = torch.rand(self.hidden_size + self.vocab_size, 
                                       self.hidden_size)
        self.params['Bo'] = torch.rand(1, self.hidden_size)

        self.params['Wv'] = torch.rand(self.hidden_size, 
                                       self.vocab_size)
        self.params['Bv'] = torch.rand(1, self.vocab_size)

        for param in self.params.values():
            param.requires_grad = True        

            
    def _zero_param_grads(self) -> None:
        for param in self.params.values():
            if param.grad is not None:
                param.grad.data.zero_() 

    
    def forward(self, input_: Tensor) -> Tensor:
        if self.first:
            self._init_params(input_)
            self.first = False        
    
        # shape: batch size by sequence length by vocab_size
        self.input_ = input_
        
        H_in = torch.clone(self.start_H)
        C_in = torch.clone(self.start_C)

        self.output = torch.zeros_like(self.input_)
        
        seq_len = self.input_.shape[1]
        
        for i in range(seq_len):
            
            # pass info forward through the nodes 
            elem_out, H_in, C_in = self.nodes[i].forward(self.params, self.input_[:, i, :], 
                                                         H_in, C_in)
            
            # define output to be 
            self.output[:, i, :] = elem_out
            
        self.start_H = H_in
        self.start_C = C_in
            
        return self.output


    def backward(self, output_grad: Tensor) -> Tensor:
        
#         self._zero_param_grads()
        
        dH_next = torch.zeros_like(self.start_H)
        dC_next = torch.zeros_like(self.start_C)

        self.input_grad = torch.zeros_like(self.input_)

        for i in reversed(range(self.input_.shape[1])):

            # pass info forward through the nodes 
            grad_out, dH_next, dC_next = \
                self.nodes[i].backward(self.params, output_grad[:, i, :], 
                                       dH_next, dC_next)
            
            # define output to be 
            self.input_grad[:, i, :] = grad_out
            
        return self.input_grad

#### Testing

In [349]:
# define input, shape: (batch_size, sequence_length, vocab_size)
batch_size = 10
sequence_length = 20
vocab_size = 62
lstm_in = torch.rand(batch_size, sequence_length, vocab_size)
lstm_in.shape

torch.Size([10, 20, 62])

In [350]:
lstm_in[:, 0, :].shape

torch.Size([10, 62])

In [351]:
# instantiate objects
lay = LSTMLayer(sequence_length, vocab_size)

In [352]:
# test passing forward
lstm_out = lay.forward(lstm_in)
print(lstm_out.shape)

tensor([[0.7616, 0.7616, 0.7616, 0.7616, 0.7616],
        [0.7616, 0.7616, 0.7616, 0.7616, 0.7616],
        [0.7616, 0.7616, 0.7616, 0.7616, 0.7616],
        [0.7616, 0.7616, 0.7616, 0.7616, 0.7616],
        [0.7616, 0.7616, 0.7616, 0.7616, 0.7616]], grad_fn=<SliceBackward>)
tensor([[0.9427, 0.9427, 0.9427, 0.9427, 0.9427],
        [0.9427, 0.9427, 0.9427, 0.9427, 0.9427],
        [0.9427, 0.9427, 0.9427, 0.9427, 0.9427],
        [0.9427, 0.9427, 0.9427, 0.9427, 0.9427],
        [0.9427, 0.9427, 0.9427, 0.9427, 0.9427]], grad_fn=<SliceBackward>)
tensor([[0.9597, 0.9597, 0.9597, 0.9597, 0.9597],
        [0.9597, 0.9597, 0.9597, 0.9597, 0.9597],
        [0.9597, 0.9597, 0.9597, 0.9597, 0.9597],
        [0.9597, 0.9597, 0.9597, 0.9597, 0.9597],
        [0.9597, 0.9597, 0.9597, 0.9597, 0.9597]], grad_fn=<SliceBackward>)
tensor([[0.9611, 0.9611, 0.9611, 0.9611, 0.9611],
        [0.9611, 0.9611, 0.9611, 0.9611, 0.9611],
        [0.9611, 0.9611, 0.9611, 0.9611, 0.9611],
        [0.9611, 0.961

In [329]:
# testing backward "retain_graph = True"
x = torch.ones(2, 2, requires_grad=True)
x1 = x + 2
x2 = x + 3
y = x1 + 2
z = x2 + 2
y.backward(torch.ones(2, 2))
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [330]:
# does retain_graph=True change anything?
x = torch.ones(2, 2, requires_grad=True)
x1 = x + 2
x2 = x + 3
y = x1 + 2
z = x2 + 2
y.backward(torch.ones(2, 2), retain_graph=True)
z.backward(torch.ones(2, 2), retain_graph=True) 
x.grad

tensor([[2., 2.],
        [2., 2.]])

In [331]:
# test backward
lstm_grad = torch.ones_like(lstm_out)
lay.backward(lstm_grad)

tensor([[[7.7725e-04, 5.7210e-04, 7.5713e-04,  ..., 7.7355e-04,
          7.4075e-04, 7.8117e-04],
         [5.5032e-20, 4.8205e-20, 5.1460e-20,  ..., 6.4384e-20,
          5.4052e-20, 4.8819e-20],
         [4.1686e-23, 4.0675e-23, 5.0620e-23,  ..., 5.5260e-23,
          3.9072e-23, 4.3622e-23],
         ...,
         [1.8779e-23, 1.1537e-23, 1.7565e-23,  ..., 1.9291e-23,
          1.2771e-23, 1.5281e-23],
         [4.1651e-24, 3.5412e-24, 2.5523e-24,  ..., 4.6605e-24,
          2.9198e-24, 3.0040e-24],
         [9.2731e-24, 1.0888e-23, 1.2496e-23,  ..., 1.3382e-23,
          1.1926e-23, 1.0415e-23]],

        [[1.2259e-04, 9.2816e-05, 1.0968e-04,  ..., 1.0683e-04,
          9.6706e-05, 1.1418e-04],
         [6.7575e-19, 6.9795e-19, 8.9514e-19,  ..., 9.2751e-19,
          7.5530e-19, 8.5921e-19],
         [1.8754e-23, 1.8340e-23, 1.7686e-23,  ..., 2.3172e-23,
          1.7370e-23, 1.6557e-23],
         ...,
         [4.5157e-23, 3.5073e-23, 3.0150e-23,  ..., 4.8005e-23,
          2.997

In [340]:
lay.params['Wf'].grad.shape

torch.Size([162, 100])

# LSTM Operations

## `LSTM Layer` 

Input: series of word embeddings, cell state.

Output: series of embeddings of the same size as the word, hidden state.

Cell state will be an attribute of the layer.

LSTM layer will have an additional function "reset state" that resets the hidden state to zero.

## `LSTM Node` 

Each LSTM layer will have a series of a special kind of operation, `LSTM Node`. These nodes will have a series of special operations: they will take in as input an embedding and a hidden state and pass out an embedding and an updated hidden state. 

Operations of LSTM Node:

Receives as input:

* X (batch size x embedding dim)
* H_prev (batch size x hidden dim)
* C_prev (batch size x hidden dim)

Diff components:

Create "Z"
Copy "Z"


1. Z = Concat(X, H)
1. Z1, Z2, Z3, Z4 = Copy(Z)
1. F = WeightMultiply(Z1, W_f)
1. F = BiasAdd(F, B_f)
1. F_out = Sigmoid(F)
1. I = WeightMultiply(Z2, W_i)
1. I = BiasAdd(I, B_i)
1. I_out = Sigmoid(I)
1. C = WeightMultiply(Z3, W_c)
1. C = BiasAdd(C, B_c)
1. C_bar = Tanh(C, B_c)
1. C1 = Multiply(F_out, C_prev)
1. C2 = Multiply(I_out, C_bar)
1. C_new = Add(C1, C2)
1. O = WeightMutiply(Z4, W_o)
1. O = Add(O, B_o)
1. O_out = Sigmoid(O)
1. C_tan = Tanh(C_new)
1. H_new = Multiply(O_out, C_tan)
1. H_out = WeightMultiply(H_new, W_v)
1. X_out = BiasAdd(H_out, B_v)

Issues:

* Concat operations needs to produce four distinct outputs. 
    * Potential solution: `Copy` operation that sums gradients.

* Need a way to handle branching:
* After `Copy`, there will be four `forward` operations happening.
* Can't write `for operation in self.operations: operation.forward(X)`
    * Maybe I can

That's it!        
1. Parameters are initialized at the `LSTMLayer` level. 
2. `LSTMNode` has a series of `ParamOperation`s.
3. At the beginning of each operation's `forward` and `backward` methods, the nodes get parameters from the `LSTMLayer`.
4. On the backward pass, they:
    * Provide `param_grad`s for each `ParamOperation`.
    * `LSTMNode` will need a function to return all of its `param_grad`s.
5. The `LSTMLayer` can get the `param_grad`s from all of the `LSTMNode`s, aggregate them.


In [ ]:
class LSTMNode(object):

    def __init__(self):

    
    
    def forward(self, 
                X_input: Tensor, 
                H_in: Tensor,
                C_in: Tensor, 
                params: Dict[Tensor]):
        
        operations_1 = [
            Concat(X_input, H_in),
            Copy(4), 
        ] 
        
        operations_2 = [
            WeightMultiply(params['W_f']),
            BiasAdd(params['B_f']),
            Sigmoid()
        ] # outputs F_out
        
        operations_3 = [
            WeightMultiply(params['W_i']),
            BiasAdd(params['B_i']),
            Sigmoid()
        ] # outputs I_out
        
        operations_4 = [
            WeightMultiply(params['W_c']),
            BiasAdd(params['B_c']),
            Tanh()
        ] # outputs C_bar
        
        operations_5 = [
            Multiply(), # outputs C1
            Multiply()
        ]

        operation_blocks = [
            [operations_1, 
             [operations_2, operations_3]
             , operations_4, oper]
            
        ]
        self.input = input

        self.output = self._output()

        return self.output


    def backward(self, output_grad: Tensor) -> Tensor:

        assert_same_shape(self.output, output_grad)

        self._compute_grads(output_grad)

        assert_same_shape(self.input, self.input_grad)
        return self.input_grad


    def _compute_grads(self, output_grad: Tensor) -> Tensor:

        self.input_grad = self._input_grad(output_grad)

        assert_same_shape(self.input, self.input_grad)
        return self.input_grad

    def _output(self) -> Tensor:
        raise NotImplementedError()

    def _input_grad(self, output_grad: Tensor) -> Tensor:
        raise NotImplementedError()

```python
Z, Z = Concat(X, H_in) # Concat takes in two inputs produces one output, will have X_grad and H_in_grad

Z_1, Z_2, Z_3 = Copy(Z, 3)

F = WeightMultiply(Z_1, W_f) 
F = BiasAdd(F, B_f)
F_out = Sigmoid(F)

I = WeightMultiply(Z_2, W_i) 
I = BiasAdd(I, B_i)
I_out = Sigmoid(I)

C = WeightMultiply(Z_3, W_c)
C = BiasAdd(C, B_c)
C_bar = Tanh(C)



Operations are the smallest units that have inputs and outputs defined by having a input and output.

Going to need to build operations that:

* Can take in one input and produce multiple outputs
* If it produces multiple outputs, _gradients will need to accumulate_.

## Toy example

* Divide two inputs into:
    * `A`, `B`
    * `A` gets copied into `A1` and `A2`
    * `A1` and `A2` each get multiplied, bias added, activation, to create `C1` and `C2`.
    * These get added together to create `D`.
    * `B` and `D` get multiplied to create `E`. 
    
Then the question is: what is the gradient of `E` with respect to `A`.

In [ ]:
def mult(*args):
    num = 1
    print(type(args))
    for arg in args:
        num *= arg
    return num

In [ ]:
mult(3)

In [ ]:
from typing import Tuple
from torch import Tensor

In [ ]:
def assert_same_shapes(tensors: Tuple[Tensor],
                       tensor_grads: Tuple[Tensor]):
    for tensor, tensor_grad in zip(tensors, tensor_grads):
        assert tensor.shape == tensor_grad.shape, \
        '''
        Two tensors should have the same shape; instead, first Tensor's shape is {0}
        and second Tensor's shape is {1}.
        '''.format(tuple(tensor_grad.shape), tuple(tensor.shape))
        return None

#### New `Operation` class

In [ ]:
class Operation(object):

    def __init__(self):
        pass

    def forward(self, *inputs) -> Tuple[Tensor]:

        self.inputs = inputs

        self.outputs = self._outputs()

        return self.outputs


    def backward(self, *output_grads) -> Tuple[Tensor]:
#         import pdb; pdb.set_trace()
        assert_same_shapes(self.outputs, output_grads)

        self._compute_grads(output_grads)

        assert_same_shapes(self.inputs, self.input_grads)
        return self.input_grads


    def _compute_grads(self, output_grads: Tuple[Tensor]) -> Tensor:
        
        self.input_grads = self._input_grads(output_grads)

        return self.input_grads

    def _outputs(self) -> Tuple[Tensor]:
        raise NotImplementedError()

    def _input_grads(self, *output_grads) -> Tuple[Tensor]:
        raise NotImplementedError()


In [ ]:
a = Tensor([1,2])
b = Tensor([3,4])
a * b

#### `Multiply`

In [ ]:
class Multiply(Operation):
   
    def __init__(self):
        pass

    def _outputs(self) -> Tuple[Tensor]:
        '''
        Element-wise multiplication
        '''
        assert len(self.inputs) == 2
        
        return (self.inputs[0] * self.inputs[1],)

    def _input_grads(self, output_grads: Tuple[Tensor]) -> Tuple[Tensor]:

        return self.inputs[1] * output_grads[0],\
               self.inputs[0] * output_grads[0]
     

In [ ]:
m = Multiply()

In [ ]:
print(m.forward(a,b))
print(m.backward(Tensor([1,1])))

#### `Add2`

In [ ]:
class Add2(Operation):
   
    def __init__(self):
        pass

    def _outputs(self) -> Tuple[Tensor]:
        '''
        Element-wise addition
        '''
        assert len(self.inputs) == 2
        
        return (self.inputs[0] + self.inputs[1],)

    def _input_grads(self, output_grads: Tuple[Tensor]) -> Tuple[Tensor]:

        return output_grads[0], output_grads[0]
     

In [ ]:
add = Add2()

In [ ]:
print(add.forward(a,b))
print(add.backward(torch.ones_like(a)))

#### `Concat`

In [82]:
a = Tensor([[1,2],[3,4]])
b = Tensor([[5,6],[7,8]])

In [ ]:
c = torch.cat([a,b], dim=1)

In [ ]:
torch.split(c, [2, 2], dim=1)

In [ ]:
tuple(inp.shape[1] for inp in (a,b))

In [84]:
class Concat2(Operation):
   
    def __init__(self):
        pass

    def _outputs(self) -> Tuple[Tensor]:
        '''
        Element-wise multiplication
        '''
        assert len(self.inputs) == 2
        
        self.input_shapes = [inp.shape[1] for inp in self.inputs]
        
        return (torch.cat(list(self.inputs), dim=1), )

    def _input_grads(self, output_grads: Tuple[Tensor]) -> Tuple[Tensor]:
        return torch.split(output_grads[0], 
                           self.input_shapes,
                           dim=1)
     

In [ ]:
cp = Copy()
out = cp.forward(a)
cp.backward(a, a)

* Divide two inputs into:
    * `A`, `B`
    * `A` gets copied into `A1` and `A2`
    * `A1` and `A2` each get multiplied, bias added, activation, to create `C1` and `C2`.
    * These get added together to create `D`.
    * `B` and `D` get multiplied to create `E`. 
    
Then the question is: what is the gradient of `E` with respect to `A`.

In [ ]:
inputs = a, b

In [ ]:
from collections import OrderedDict

In [ ]:
OrderedDict?

In [ ]:
from itertools import OrderedDict

In [ ]:
ops_1 = [Copy()]
ops_2 = [[[WeightMultiply(w1), BiasAdd(b1), Sigmoid()],
          [WeightMultiply(w1), BiasAdd(b1), Sigmoid()]],
         Add2()]
ops_3 = [Multiply()]

In [ ]:
forward_op(ops_1, a)

Three cases:

* If `op` is an operation, simply call forward.
* If `op` is a list and `op[0]` is an operation, call `forward_op` on all the operations in `op`
* If `op` is a list and `op[0]` is a list, call `forward_op` on `op` and `inputs`.

In [ ]:
def forward_op(ops, *inputs):
    out = inputs
    for op in ops:
        if isinstance(op, list):
            if isinstance(op[0], list):
                out = tuple(forward_op(operation, inp) for operation, inp in zip(op, out))
            else:
                

            
        if len(out) == 1:
            out = op.forward(out[0])
        else:
            out = op.forward(out)
        
    return out

If type of op is list, that means we want to apply the first element of the list to the 

In [ ]:
forward_op(ops_2, forward_op(ops_1, a))

In [ ]:

e = forward_op(ops_3, b, forward_op(ops_2, forward_op(ops_1, a)))

In [ ]:
def mult(start, *args):
    res = start
    for num in args:
        res *= num
    return res

Good. Now how to do the backward pass?

In [ ]:
class ParamOperation(Operation):

    def __init__(self, param: Tensor) -> Tensor:
        super().__init__()
        self.param = param


    def _compute_grads(self, output_grads: Tuple[Tensor]) -> Tensor:
        self.input_grad = self._input_grad(output_grads)
        self.param_grad = self._param_grad(output_grads)


    def _param_grad(self, output_grad: Tensor) -> Tensor:
        raise NotImplementedError()


In [ ]:
class WeightMultiply(ParamOperation):

    def __init__(self, W: Tensor):
        super().__init__(W)

    def _outputs(self) -> Tensor:
        return (torch.mm(self.inputs[0], self.param), )

    def _input_grads(self, output_grad: Tensor) -> Tensor:
        return (torch.mm(output_grad[0], self.param.transpose(0, 1)), )

    def _param_grad(self, output_grad: Tensor) -> Tensor:
        return torch.mm(self.inputs[0].transpose(0, 1), output_grad[0])


class BiasAdd(ParamOperation):

    def __init__(self,
                 B: Tensor):
        super().__init__(B)


    def _outputs(self) -> Tensor:
        return (torch.add(self.inputs[0], self.param), )


    def _input_grads(self, output_grads: Tuple[Tensor]) -> Tensor:
        return (torch.ones_like(self.inputs[0]) * output_grad[0], )


    def _param_grad(self, output_grads: Tuple[Tensor]) -> Tensor:
        param_grad = torch.ones_like(self.param) * output_grad[0]
        return torch.sum(param_grad, dim=0).reshape(1, param_grad.shape[1])

In [ ]:
class Sigmoid(Operation):
    '''
    Sigmoid activation function
    '''
    def __init__(self) -> None:
        super().__init__()


    def _outputs(self) -> Tuple[Tensor]:
        return (1.0/(1.0+torch.exp(-1.0 * self.input)), )


    def _input_grad(self, output_grad: Tensor) -> Tensor:
        sigmoid_backward = self.output * (1.0 - self.output)
        input_grad = sigmoid_backward * output_grad
        return (input_grad, )

    def __repr__(self):
        return "Sigmoid"

First: copy, and then weight multiply each.

In [ ]:
torch.rand?

In [ ]:
torch.manual_seed(101218)
op1 = Copy()
w1, w2 = torch.rand(2,2), torch.rand(2,2)
b1, b2 = torch.rand(1,2), torch.rand(1,2)
op2, op3 = WeightMultiply(w1), WeightMultiply(w2)
ops2 = [op2, op3]
stages = [[op1], ops2]

In [ ]:
stage_in = (a,)
for stage in stages:
    stage_out = tuple()
    for i, op in enumerate(stage):
        stage_out = stage_out + op.forward(stage_in[i])
    stage_in = stage_out
final_out = stage_out

In [ ]:
def ones_like_multiple(output: Tuple[Tensor]) -> Tuple[Tensor]:
    return tuple(torch.ones_like(tensor) for tensor in output)

In [ ]:
full_ops

In [ ]:
full_ops = [[[WeightMultiply(w1), BiasAdd(b1), Sigmoid()], 
             [WeightMultiply(w1), BiasAdd(b1), Sigmoid()]], Add2()]

Step 1: full_ops[0]

In [ ]:
len(full_ops)

In [ ]:
full_ops[0]

We see a list of lists. It has length 2. 

That means ultimately, we want the first input to go through the first argument, and the second input to go through the second.

In [ ]:
full_ops[0][0]

Now we have a non-nested list. This signals: take the first argument, and feed it through.

In [ ]:
full_ops[0][1]

Here we have another non-nested list. We must similarly: take the second argument, and feed it through. 

Now we'll have two outputs, at the end of `full_ops[0]`. We move on the `full_ops[1]`, which indeed is:

In [ ]:
full_ops[1]

In [ ]:
def is_nested_list(nested_list):
    for el in nested_list:
        if isinstance(el, list):
            return True
    return False

#### Manual walkthrough: `full_ops_advanced`

In [ ]:
full_ops_advanced = [Copy(), 
  [[WeightMultiply(w1), BiasAdd(b1), Sigmoid()], 
   [WeightMultiply(w1), BiasAdd(b1), Sigmoid()]],
  Add2()],
 Multiply()]

In [ ]:
full_ops_advanced

We have a list of length 2. This means: pass the first element to the first branch, and the second element to the second branch.

In [ ]:
full_ops_advanced[0]

This is still a nested list. However, the first element is an operation. So, we want to start by feeding this element through the `Operation`.

In [ ]:
full_ops_advanced[0][0]

This outputs two things, and indeed:

In [ ]:
full_ops_advanced[0][1]

Is of length two.

So, we have:

* If the first element in the list is an operation, feed the input through it, and keep doing so until you reach an element in the list that is not an `Operation`.
* At some point, you'll have outputs from the `Operation`s, and another (possibly nested) list of operations to deal with. At this point, you should call the main function again, with the `output`s from the first part, and the new operations. This function should return a number of outputs equal to the length of the list.
* At this point, we'll have two outputs, and we'll move on to:

In [ ]:
full_ops_advanced[0][2]

We'll take the outputs from the prior section and feed them through this function.

Finally, we reach another function. Since this function is next in the list, our code will have to assume that it 

This nested list structure cannot support branching. Need to try another approach.

In [ ]:
full_ops_advanced[1]

# New approach: using PyTorch's `autograd` feature